- id: '1642022966347'
  alias: Start Transmission Automation
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.start_transmission_switch
    to: 'on'
  condition: []
  action:
  - service: shell_command.start_transmission
  mode: single

- id: '1642096194840'
  alias: Landing Light - Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 50ac688f3a0bd8a434c9a8f7766d2f4e
    entity_id: binary_sensor.motion_landing_ias_zone
    domain: binary_sensor
  condition:
  - type: is_illuminance
    condition: device
    device_id: 50ac688f3a0bd8a434c9a8f7766d2f4e
    entity_id: sensor.motion_landing_illuminance
    domain: sensor
    below: 15
  action:
  - type: turn_on
    device_id: 0c744a92a7a2e4a0bce5b021913d4df8
    entity_id: light.landing_main
    domain: light
  mode: single

- id: '1642104788833'
  alias: Landing Light - No Motion
  description: Landing automation when there is no motion detected.
  trigger:
  - type: no_motion
    platform: device
    device_id: 50ac688f3a0bd8a434c9a8f7766d2f4e
    entity_id: binary_sensor.motion_landing_ias_zone
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition:
  - condition: device
    type: is_on
    device_id: 0c744a92a7a2e4a0bce5b021913d4df8
    entity_id: light.landing_main
    domain: light
  action:
  - type: turn_off
    device_id: 0c744a92a7a2e4a0bce5b021913d4df8
    entity_id: light.landing_main
    domain: light
  mode: single

- id: '1642152823912'
  alias: Slow Internet Notification
  description: ''
  trigger:
  - type: value
    platform: device
    device_id: 40e53100c9eb6965f19dc95fd528e0aa
    entity_id: sensor.speedtest_download
    domain: sensor
    below: 30
  condition: []
  action:
  - device_id: b460bab4803cdd84e2a5ec86f10a3351
    domain: mobile_app
    type: notify
    message: Internet is running slow.
    title: Internet Slow
  mode: single
  
- id: '1642159359141'
  alias: Study Dimmer Switch
  description: ''
  trigger:
  - device_id: f3b5dbef5fe49c8dd80a269a2dbd4b3e
    domain: hue
    platform: device
    type: initial_press
    subtype: 1
    unique_id: a58ddbe7-485e-4d9b-817e-d5b1bb43e5b4
  condition: []
  action:
  - type: turn_on
    device_id: 07bda9b16717d442c93a0c60113bcd34
    entity_id: light.study_main_light
    domain: light
    brightness_pct: 50
  mode: single

- id: '1642684462952'
  alias: Stop Transmission Automation
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.start_transmission_switch
    to: 'off'
  condition: []
  action:
  - service: shell_command.stop_transmission
  mode: single

- id: '1642771051750'
  alias: Kitchen Lights - Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: d09ea80a8f1f254e4c3b19e099bb7dbf
    entity_id: binary_sensor.motion_kitchen_ias_zone
    domain: binary_sensor
  condition:
  - type: is_illuminance
    condition: device
    device_id: d09ea80a8f1f254e4c3b19e099bb7dbf
    entity_id: sensor.motion_kitchen_illuminance
    domain: sensor
    below: 15
  action:
  - type: turn_on
    device_id: 2abeb784892de00f1b8a2114cf642e80
    entity_id: light.spotlight_1
    domain: light
  - type: turn_on
    device_id: 560d4baddbc21311773b2b11f465c9de
    entity_id: light.spotlight_2
    domain: light
  - type: turn_on
    device_id: 7fc3147dc417105514a32b442a405091
    entity_id: light.spotlight_3
    domain: light
  mode: single

- id: '1642771097034'
  alias: Kitchen Lights - No Motion
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: d09ea80a8f1f254e4c3b19e099bb7dbf
    entity_id: binary_sensor.motion_kitchen_ias_zone
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 2abeb784892de00f1b8a2114cf642e80
    entity_id: light.spotlight_1
    domain: light
  - type: turn_off
    device_id: 560d4baddbc21311773b2b11f465c9de
    entity_id: light.spotlight_2
    domain: light
  - type: turn_off
    device_id: 7fc3147dc417105514a32b442a405091
    entity_id: light.spotlight_3
    domain: light
  mode: single

- id: '1642771675615'
  alias: Hall - Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 122796725d3ba1d0ced421910698d8fc
    entity_id: binary_sensor.motion_hall_ias_zone
    domain: binary_sensor
  condition:
  - type: is_illuminance
    condition: device
    device_id: 122796725d3ba1d0ced421910698d8fc
    entity_id: sensor.motion_hall_illuminance
    domain: sensor
    below: 15
  - condition: device
    type: is_off
    device_id: 6472af1ddd2cb2bfee4f5b17d4e7e5dd
    entity_id: light.hall_main_light
    domain: light
  action:
  - type: turn_on
    device_id: 6472af1ddd2cb2bfee4f5b17d4e7e5dd
    entity_id: light.hall_main_light
    domain: light
  mode: single

- id: '1642771716016'
  alias: Hall - No Motion
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 122796725d3ba1d0ced421910698d8fc
    entity_id: binary_sensor.motion_hall_ias_zone
    domain: binary_sensor
  condition:
  - condition: device
    type: is_on
    device_id: 6472af1ddd2cb2bfee4f5b17d4e7e5dd
    entity_id: light.hall_main_light
    domain: light
  action:
  - type: turn_off
    device_id: 6472af1ddd2cb2bfee4f5b17d4e7e5dd
    entity_id: light.hall_main_light
    domain: light
  mode: single

- id: '1642795358412'
  alias: Study - Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 7e519494982423440d3df00c21536371
    entity_id: binary_sensor.motion_study_ias_zone
    domain: binary_sensor
  condition:
  - type: is_illuminance
    condition: device
    device_id: 7e519494982423440d3df00c21536371
    entity_id: sensor.motion_study_illuminance
    domain: sensor
    below: 15
  action:
  - type: turn_on
    device_id: d88601dbe030640ba70439c983361071
    entity_id: light.study_strip_light
    domain: light
    brightness_pct: 100
  mode: single

- id: '1642795520427'
  alias: Study - No Motion
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 7e519494982423440d3df00c21536371
    entity_id: binary_sensor.motion_study_ias_zone
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: d88601dbe030640ba70439c983361071
    entity_id: light.study_strip_light
    domain: light
  mode: single

- id: '1642935294943'
  alias: Study 2 - Motion
  description: ''
  trigger:
  - type: motion
    platform: device
    device_id: 34c00b160cac87cf2b7c75e210493697
    entity_id: binary_sensor.motion_study_ias_zone
    domain: binary_sensor
  condition:
  - type: is_illuminance
    condition: device
    device_id: 50ac688f3a0bd8a434c9a8f7766d2f4e
    entity_id: sensor.motion_landing_illuminance
    domain: sensor
    below: 15
  action:
  - type: turn_on
    device_id: 65dd4e38906771c99abee8458be94306
    entity_id: light.study_2_main
    domain: light
  mode: single

- id: '1642935366431'
  alias: Study 2 - No Motion
  description: ''
  trigger:
  - type: no_motion
    platform: device
    device_id: 34c00b160cac87cf2b7c75e210493697
    entity_id: binary_sensor.motion_study_2_ias_zone
    domain: binary_sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - type: turn_off
    device_id: 65dd4e38906771c99abee8458be94306
    entity_id: light.study_2_main
    domain: light
  mode: single

- id: '1647450902261'
  alias: Water Fountain - Turn on
  description: ''
  trigger:
  - platform: time
    at: 07:30:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.orvibo_switch_1
  mode: single
