- platform: rest
  resource: !secret bt_availability_endpoint
  name: "BT Gigabit Availability"
  method: "GET"
  device_class: "connectivity"
  timeout: 30000
  scan_interval: 3600
  headers:
    Content-Type: application/json
  value_template: >
      {%- for serviceLineType in value_json.serviceLineTypes -%}
        {%- if serviceLineType.speed == "1000M" -%}
          {{ "on" }}
        {%- endif -%}
      {%- endfor -%}